INSERT INTO directory (firstName, lastName, age, address, phone, email, username, pword, verified, shown, late, penalized, owe, guests, keepAccount, keepConfirm, annual) VALUES ("John", "Doe", 21, "1 Main Street,\nWest Hartford, CT,\n06117", "4353234432", "john@tennis.com", "jdoe", "pass", true, false, false, false, 0, 0, true, true, 0);
INSERT INTO directory (firstName, lastName, age, address, phone, email, username, pword, verified, shown, late, penalized, owe, guests, keepAccount, keepConfirm, annual) VALUES ("Jane", "Smith", 67, "123 Main Street, \nNew Britain, CT,\n06050", "9758495847", "jane@gmail.com", "jsmith", "pass", true, true, true, false, 0, 0, true, true, 1300);
INSERT INTO directory (firstName, lastName, age, address, phone, email, username, pword, verified, shown, late, penalized, owe, guests, keepAccount, keepConfirm, annual) VALUES ("Adam", "Fincher", 33, "123 Second Street, \nEast Hartford, CT,\n06108", "7598495847", "admin9999@admin.com", "admin", "pass", true, false, false, false, 0, 0, true, true, 0);

INSERT INTO bank (username, bankName, accountNum, ssn, accountType, total) values ("jsmith", "citizens bank", "123456789", "123456789", "Checking", 8000);

INSERT INTO waiting (firstName, lastName, age, address, phone, email, username, pword, shown, owe) VALUES ("Paul", "Anderson", 53, "82 Magnolia Street,\nSan Tropez, CA,\n568493", "1234567898", "ttwb@gmail.com", "pta", "pass", true, 0);
INSERT INTO waiting (firstName, lastName, age, address, phone, email, username, pword, shown, owe) VALUES ("Stanley", "Kubrick", 92, "9000 Hal Avenue,\nBrooklyn, NY,\n46372", "1234567898", "lyndon@aol.com", "hal", "pass", true, 0);
INSERT INTO waiting (firstName, lastName, age, address, phone, email, username, pword, shown, owe) VALUES ("David", "Fincher", 63, "95 Mills Blvd,\nSummerset, CT,\n06117", "1234567898", "durden@gmail.com", "jack", "pass", true, 0);
INSERT INTO waiting (firstName, lastName, age, address, phone, email, username, pword, shown, owe) VALUES ("Billy", "Wilder", 28, "50 Sunset Blvd,\nHollywood, CA,\n64738", "1234567898", "ace@gmail.com", "billy", "pass", true, 0);
INSERT INTO waiting (firstName, lastName, age, address, phone, email, username, pword, shown, owe) VALUES ("Penelope", "Spherres", 17, "1 Aurora Lane,\nVentura, CA,\n06117", "1234567898", "declineofwesciv@gmail.com", "wayne", "pass", true, 0);